name: Kernel Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 --branch stable-susfs https://github.com/UdayKumarChunduru/fusionX_sm8250.git kernel

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libelf-dev flex bison libncurses-dev zstd
          wget https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst -O clang.tar.zst
          mkdir -p clang-neutron
          unzstd -d clang.tar.zst
          tar -xf clang.tar -C clang-neutron
          echo "CLANG_PATH=$(pwd)/clang-neutron/bin" >> $GITHUB_ENV

          cd kernel
          echo "🔧 Applying KernelSU manager patch..."
          bash nextpatch.sh

      - name: Build Kernel
        run: |
          echo "CLANG_PATH is: $CLANG_PATH"
          ls -la $CLANG_PATH/
          export PATH="$CLANG_PATH:$PATH"
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="senx"
          export KBUILD_BUILD_HOST="ubuntu"
          export KBUILD_BUILD_TIMESTAMP="$(TZ=UTC-7 date)"

          cd kernel
          make O=out vendor/munch_defconfig

          # Append important config flags
          cat <<EOF >> out/.config
          CONFIG_KALLSYMS=y
          CONFIG_KALLSYMS_ALL=y
          CONFIG_KPM=y
          CONFIG_TMPFS_XATTR=y
          EOF

          make O=out olddefconfig

          grep CONFIG_KALLSYMS out/.config
          grep CONFIG_KPM out/.config
          grep TMPFS_XATTR out/.config

          make O=out CC=clang -j$(nproc --all) CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1

          echo "✅ Kernel build completed successfully"
          grep -rI "CONFIG_KALLSYMS_ALL=n" . || true

      - name: Debug - Check kernel artifacts
        run: |
          cd kernel/out/arch/arm64/boot
          echo "Files in boot directory:"
          ls -la
          echo "File sizes:"
          du -h *

      - name: Apply KPM Patch
        run: |
          set -x
          grep -rI "CONFIG_KALLSYMS_ALL=n" . || true
          cd kernel/out/arch/arm64/boot
          grep -rI "CONFIG_KALLSYMS_ALL=n" . || true

          echo "🔧 Applying KPM patch..."
          curl -LSs "https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.12.0/patch_linux" -o patch
          chmod +x patch
          ./patch

          # Don't gzip the Image — keep it uncompressed
          echo "✅ KPM patch applied successfully to uncompressed Image"

      - name: Clone AnyKernel3
        run: |
          git clone --depth=1 https://github.com/SenseiiX/AnyKernel3.git anykernel

      - name: Package Kernel with AnyKernel3
        run: |
          # Copy kernel artifacts to AnyKernel3 directory
          cp kernel/out/arch/arm64/boot/Image anykernel/
          cp kernel/out/arch/arm64/boot/dtbo.img anykernel/
          cp kernel/out/arch/arm64/boot/dtb anykernel/

          # Create ZIP file
          cd anykernel
          zip -r9 ../kernel-build-$(date +%Y%m%d-%H%M).zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: kernel-build-*.zip
